# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f3d30d5ec7e2c2f1e59f3a817e2ad32820ff536d8e4a022d64e68acc8e65bf930e64c80356d5dfaff41a6121f4fecd31280b817056207429804de80103b005b0

test:
  secret_key_base: f9e34f48a44f971d11748f1ee5c5cd56ce370bcd5646df1ce3009b9075285d097fc495a4d1f8ecffb0cb7470f76fe05ad2bddb8d4dc4c9c6edd0891df4cd5221

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
